# Generated by Django 6.0.5 on 2026-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
